#!/usr/bin/env python3
"""Select high-confidence pseudo ground truth from Qwen demoire candidates.

This script is a conservative bootstrap filter. It combines low-frequency
content preservation, color preservation, edge/detail preservation, and
suppression of input-specific periodic spectral peaks. Groups that fail hard
constraints or confidence thresholds are rejected instead of being forced into
the pseudo-GT bank.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
from collections import defaultdict
from pathlib import Path
from typing import Iterable

import numpy as np
from PIL import Image, ImageFilter


EPS = 1e-8


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Select high-confidence pseudo GT from grouped Qwen candidates."
    )
    parser.add_argument("--metadata", type=Path, required=True)
    parser.add_argument("--output_dir", type=Path, required=True)
    parser.add_argument(
        "--mode",
        choices=("base", "lora"),
        default="base",
        help="Select candidates generated by this inference mode.",
    )
    parser.add_argument("--metric_size", type=int, default=384)
    parser.add_argument("--peak_percentile", type=float, default=97.0)
    parser.add_argument("--min_content", type=float, default=0.78)
    parser.add_argument("--min_color", type=float, default=0.78)
    parser.add_argument("--min_detail", type=float, default=0.50)
    parser.add_argument("--max_detail_ratio", type=float, default=2.20)
    parser.add_argument("--min_confidence", type=float, default=0.62)
    parser.add_argument("--min_margin", type=float, default=0.015)
    parser.add_argument(
        "--copy_rejected_best",
        action="store_true",
        help="Also copy the best candidate of rejected groups for manual review.",
    )
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def read_jsonl(path: Path) -> Iterable[dict]:
    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            line = raw_line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at {path}:{line_number}: {exc}") from exc


def write_jsonl(path: Path, records: Iterable[dict]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")


def resolve_record_path(value: str, metadata_path: Path) -> Path:
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = metadata_path.parent / path
    return path.resolve()


def image_to_array(path: Path, size: int) -> np.ndarray:
    with Image.open(path) as image:
        image = image.convert("RGB")
        image.thumbnail((size, size), Image.Resampling.LANCZOS)
        canvas = Image.new("RGB", (size, size), tuple(np.asarray(image).mean(axis=(0, 1)).astype(int)))
        left = (size - image.width) // 2
        top = (size - image.height) // 2
        canvas.paste(image, (left, top))
        return np.asarray(canvas, dtype=np.float32) / 255.0


def gaussian_blur(array: np.ndarray, radius: float) -> np.ndarray:
    image = Image.fromarray(np.clip(array * 255.0, 0, 255).astype(np.uint8))
    blurred = image.filter(ImageFilter.GaussianBlur(radius=radius))
    return np.asarray(blurred, dtype=np.float32) / 255.0


def rgb_to_gray(array: np.ndarray) -> np.ndarray:
    return 0.299 * array[..., 0] + 0.587 * array[..., 1] + 0.114 * array[..., 2]


def gradient_energy(gray: np.ndarray) -> float:
    dx = np.diff(gray, axis=1)
    dy = np.diff(gray, axis=0)
    return float((np.mean(np.abs(dx)) + np.mean(np.abs(dy))) * 0.5)


def periodic_peak_energy(input_gray: np.ndarray, output_gray: np.ndarray, percentile: float) -> tuple[float, float]:
    input_low = gaussian_blur(np.repeat(input_gray[..., None], 3, axis=2), 3.0)[..., 0]
    output_low = gaussian_blur(np.repeat(output_gray[..., None], 3, axis=2), 3.0)[..., 0]
    input_high = input_gray - input_low
    output_high = output_gray - output_low

    window = np.outer(np.hanning(input_gray.shape[0]), np.hanning(input_gray.shape[1]))
    input_power = np.abs(np.fft.fftshift(np.fft.fft2(input_high * window))) ** 2
    output_power = np.abs(np.fft.fftshift(np.fft.fft2(output_high * window))) ** 2

    height, width = input_power.shape
    yy, xx = np.ogrid[:height, :width]
    cy, cx = height // 2, width // 2
    radius = np.sqrt((yy - cy) ** 2 + (xx - cx) ** 2)
    valid = (radius >= min(height, width) * 0.04) & (radius <= min(height, width) * 0.45)
    threshold = np.percentile(input_power[valid], percentile)
    peak_mask = valid & (input_power >= threshold)

    input_energy = float(input_power[peak_mask].mean()) if peak_mask.any() else 0.0
    output_energy = float(output_power[peak_mask].mean()) if peak_mask.any() else 0.0
    ratio = output_energy / (input_energy + EPS)
    reduction = float(np.clip(1.0 - ratio, -1.0, 1.0))
    score = float(np.clip((reduction + 0.15) / 1.15, 0.0, 1.0))
    return score, ratio


def score_candidate(input_array: np.ndarray, output_array: np.ndarray, args: argparse.Namespace) -> dict:
    blur_radius = max(args.metric_size / 64.0, 2.0)
    input_low = gaussian_blur(input_array, blur_radius)
    output_low = gaussian_blur(output_array, blur_radius)

    low_mae = float(np.mean(np.abs(input_low - output_low)))
    content_score = float(np.clip(1.0 - low_mae / 0.20, 0.0, 1.0))

    input_color = input_low.mean(axis=(0, 1))
    output_color = output_low.mean(axis=(0, 1))
    color_distance = float(np.mean(np.abs(input_color - output_color)))
    color_score = float(math.exp(-color_distance / 0.08))

    input_gray = rgb_to_gray(input_array)
    output_gray = rgb_to_gray(output_array)
    input_gradient = gradient_energy(input_gray)
    output_gradient = gradient_energy(output_gray)
    detail_ratio = output_gradient / (input_gradient + EPS)
    detail_score = float(math.exp(-abs(math.log(max(detail_ratio, EPS)))))

    moire_score, spectral_ratio = periodic_peak_energy(
        input_gray,
        output_gray,
        args.peak_percentile,
    )

    valid = (
        content_score >= args.min_content
        and color_score >= args.min_color
        and detail_score >= args.min_detail
        and detail_ratio <= args.max_detail_ratio
    )
    composite = (
        0.40 * moire_score
        + 0.30 * content_score
        + 0.15 * color_score
        + 0.15 * detail_score
    )

    return {
        "content_score": content_score,
        "color_score": color_score,
        "detail_score": detail_score,
        "detail_ratio": float(detail_ratio),
        "moire_spectral_score": moire_score,
        "spectral_energy_ratio": float(spectral_ratio),
        "composite_score": float(composite),
        "hard_constraints_passed": bool(valid),
    }


def safe_group_name(group_id: str) -> str:
    cleaned = "".join(c if c.isalnum() or c in "-_." else "_" for c in group_id)
    return cleaned.strip("._") or "sample"


def copy_selected(source: Path, destination: Path, overwrite: bool) -> None:
    if destination.exists() and not overwrite:
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def main() -> None:
    args = parse_args()
    metadata_path = args.metadata.expanduser().resolve()
    if not metadata_path.is_file():
        raise FileNotFoundError(f"Metadata does not exist: {metadata_path}")

    groups: dict[str, list[dict]] = defaultdict(list)
    for record in read_jsonl(metadata_path):
        if record.get("mode") != args.mode:
            continue
        group_id = str(record.get("group_id") or record.get("sample_id"))
        groups[group_id].append(record)

    if not groups:
        raise ValueError(f"No mode={args.mode!r} candidate records found in {metadata_path}")

    output_dir = args.output_dir.expanduser().resolve()
    selected_dir = output_dir / "images"
    rejected_dir = output_dir / "manual_review"
    output_dir.mkdir(parents=True, exist_ok=True)

    selected_records=[]
    rejected_records=[]
    all_candidate_records=[]

    for group_index, (group_id, records) in enumerate(sorted(groups.items())):
        records.sort(key=lambda record: int(record.get("candidate_index", 0)))
        input_path = resolve_record_path(records[0]["input_image"], metadata_path)
        if not input_path.is_file():
            raise FileNotFoundError(f"Input image does not exist: {input_path}")
        input_array = image_to_array(input_path, args.metric_size)

        scored=[]
        for record in records:
            output_path = resolve_record_path(record["output_image"], metadata_path)
            if not output_path.is_file():
                print(f"[Missing] {output_path}", flush=True)
                continue
            output_array = image_to_array(output_path, args.metric_size)
            metrics = score_candidate(input_array, output_array, args)
            enriched = dict(record)
            enriched["reward_vector"] = metrics
            enriched["output_image"] = str(output_path)
            enriched["input_image"] = str(input_path)
            scored.append(enriched)
            all_candidate_records.append(enriched)

        valid = [record for record in scored if record["reward_vector"]["hard_constraints_passed"]]
        valid.sort(key=lambda record: record["reward_vector"]["composite_score"], reverse=True)

        if valid:
            best = valid[0]
            best_score = best["reward_vector"]["composite_score"]
            second_score = valid[1]["reward_vector"]["composite_score"] if len(valid) > 1 else 0.0
            margin = best_score - second_score
            hard_floor = min(
                best["reward_vector"]["content_score"],
                best["reward_vector"]["color_score"],
                best["reward_vector"]["detail_score"],
            )
            confidence = float(np.clip(0.55 * best_score + 0.25 * hard_floor + 0.20 * min(margin / 0.10, 1.0), 0.0, 1.0))
        else:
            best = max(scored, key=lambda record: record["reward_vector"]["composite_score"], default=None)
            margin = 0.0
            confidence = 0.0

        accepted = bool(
            best is not None
            and best["reward_vector"]["hard_constraints_passed"]
            and confidence >= args.min_confidence
            and margin >= args.min_margin
        )

        group_result = {
            "group_id": group_id,
            "input_image": str(input_path),
            "candidate_count": len(scored),
            "selected_as_pseudo_gt": accepted,
            "confidence": confidence,
            "top1_top2_margin": margin,
            "selected_candidate_index": best.get("candidate_index") if best else None,
            "selected_candidate": best.get("output_image") if best else None,
            "reward_vector": best.get("reward_vector") if best else None,
            "bank_version": best.get("bank_version") if best else None,
            "teacher_checkpoint": best.get("teacher_checkpoint") if best else None,
        }

        if accepted:
            suffix=Path(best["output_image"]).suffix.lower() or ".png"
            destination=selected_dir / f"{safe_group_name(group_id)}{suffix}"
            copy_selected(Path(best["output_image"]),destination,args.overwrite)
            group_result["pseudo_gt_image"] = str(destination)
            selected_records.append(group_result)
        else:
            group_result["rejection_reason"] = (
                "no_candidate_passed_hard_constraints"
                if not valid
                else "confidence_or_margin_below_threshold"
            )
            rejected_records.append(group_result)
            if args.copy_rejected_best and best is not None:
                destination=rejected_dir / f"{safe_group_name(group_id)}.png"
                copy_selected(Path(best["output_image"]),destination,args.overwrite)

        print(
            f"[{group_index + 1}/{len(groups)}] {group_id}: "
            f"accepted={accepted}, confidence={confidence:.4f}, margin={margin:.4f}",
            flush=True,
        )

    write_jsonl(output_dir / "candidate_scores.jsonl",all_candidate_records)
    write_jsonl(output_dir / "selected_pseudo_gt.jsonl",selected_records)
    write_jsonl(output_dir / "rejected_groups.jsonl",rejected_records)

    summary={
        "metadata":str(metadata_path),
        "mode":args.mode,
        "groups":len(groups),
        "selected":len(selected_records),
        "rejected":len(rejected_records),
        "selection_rate":len(selected_records)/max(len(groups),1),
        "thresholds":{
            "min_content":args.min_content,
            "min_color":args.min_color,
            "min_detail":args.min_detail,
            "max_detail_ratio":args.max_detail_ratio,
            "min_confidence":args.min_confidence,
            "min_margin":args.min_margin,
        },
        "warning":"Heuristic bootstrap scores require human/VLM audit before student training.",
    }
    with (output_dir / "selection_summary.json").open("w",encoding="utf-8") as handle:
        json.dump(summary,handle,ensure_ascii=False,indent=2)

    print(json.dumps(summary,ensure_ascii=False,indent=2),flush=True)


if __name__ == "__main__":
    main()
